questions=[
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the 1988 film &quot;Akira&quot;, Tetsuo ends up destroying Tokyo.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "hard",
            "question": "Japan was part of the Allied Powers during World War I.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The movie &quot;The Nightmare before Christmas&quot; was all done with physical objects.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Arcade Fire&#039;s &#039;The Suburbs&#039; won the Album of the Year award in the 2011 Grammys.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Gumbo is a stew that originated in Louisiana.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Super Mario Bros. was released in 1990.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Vehicles",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Japanese Shinkansen beat the French TGV&#039;s speed record for fastest electric rail train.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Assyrian king Sennacherib&#039;s destruction of Babylon in 689 BCE was viewed as a triumph by other Assyrian citizens.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There is a city called Rome in every continent on Earth.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The first Maxis game to feature the fictional language &quot;Simlish&quot; was The Sims (2000).",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The sum of all the numbers on a roulette wheel is 666.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "hard",
            "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Bulls are attracted to the color red.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Anatomy considers the forms of macroscopic structures such as organs and organ systems.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The term &quot;Spam&quot; came before the food product &quot;Spam&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Comics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Deadpool&#039;s identity is Slade Wilson.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The open source program Redis is a relational database server.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "hard",
            "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Board Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There is a Donald Trump Board Game, which was made in 1989.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "United States President Ronald Reagan was the first president to appoint a woman to the Supreme Court. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Adolf Hitler was born in Australia. ",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "hard",
            "question": "Joko Widodo has appeared in the cover of a TIME magazine.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Linux was first created as an alternative to Windows XP.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science & Nature",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The chemical element Lithium is named after the country of Lithuania.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In Rugby League, performing a &quot;40-20&quot; is punished by a free kick for the opposing team.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Politics",
            "type": "boolean",
            "difficulty": "hard",
            "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the &quot;To Love-Ru&quot; series, Golden Darkness is sent to kill Lala Deviluke.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Japanese Anime & Manga",
            "type": "boolean",
            "difficulty": "hard",
            "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Animals",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Finnish Lapphund dogs were used for herding reindeer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Mythology",
            "type": "boolean",
            "difficulty": "easy",
            "question": "A wyvern is the same as a dragon.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "hard",
            "question": "The singer Billie Holiday was also known as &quot;Lady Day&quot;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Science: Mathematics",
            "type": "boolean",
            "difficulty": "easy",
            "question": "An equilateral triangle always has every angle measuring 60&deg;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Music",
            "type": "boolean",
            "difficulty": "easy",
            "question": "John Williams composed the music for &quot;Star Wars&quot;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Animals",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Rabbits are carnivores.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Sports",
            "type": "boolean",
            "difficulty": "easy",
            "question": "There are a total of 20 races in Formula One 2016 season.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "easy",
            "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "History",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Franz Joseph I was the last emperor of Austria.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Film",
            "type": "boolean",
            "difficulty": "hard",
            "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "easy",
            "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ]
